sass_dir         = "/"
http_path        = "../"
css_dir          = "../"
images_dir       = "../"
javascripts_dir  = "../js"
relative_assets  = true
output_style     = :expanded
environment      = :development
sass_options     = {:debug_info=>false}
line_comments    = false
preferred_syntax = :scss
