name: CSS Code Linting

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint-css:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: npm install
        run: npm install
      - name: Lint CSS
        run: npm run lint:scss
